### ISSUE TITLE
XOR encrypted shellcode

### ISSUE THREAD

**Issue by sec13b** [maxbarkouras/Syscall-Shellcode-Injector#1]
a generated payload stage from Cobalt Strike dont work.

**Comment by maxbarkouras** [comment]
Hey, I should have specified in the readme and have added it since, but the shellcode must be XOR encrypted before you paste it into the code. The syscalls are also exclusively hardcoded for the most up to date platform, Windows 11 23H2, but I'm working on a syswhispers installation to make it compatible with Windows 10 versions. If you don't want to XOR encode your shellcode beforehand, you can just comment out line 33, `xor_decrypt(shellcode, ciphertext_length, key);`, and it will run perfectly, assuming you're using Windows 11 23H2 or a version with the same syscall stub locations. If you need help with anything add me on discord, .cadenus.

**Comment by sec13b** [comment]
thank you

**Comment by sec13b** [comment]
can you recommend something to encrypt xor the shellcode.

thank you

**Comment by maxbarkouras** [comment]
add me on discord .cadenus.

**Comment by sec13b** [comment]
sec13.b
